name: Automation Testing

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: appium install
      run: npm install -g appium 
    - name: adb device
      run: sudo apt-get install android-sdk-platform-tools
    - name: adb connect
      run: adb connect 192.168.0.132:5037
    - name: Build with Maven
      run: mvn -B package --file pom.xml
